DELETE FROM voto WHERE EXISTS (SELECT 1 FROM voto);
DELETE FROM sessao_votacao WHERE EXISTS (SELECT 1 FROM sessao_votacao);
DELETE FROM pauta WHERE EXISTS (SELECT 1 FROM pauta);
DELETE FROM usuario WHERE EXISTS (SELECT 1 FROM usuario);
